---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Enable unattended-upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    mode: '0644'

- name: Allow ansible user to run sudo without password
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ninjacloud-ansible
    content: |
      {{ common_ansible_user }} ALL=(ALL) NOPASSWD: ALL
    mode: '0440'
    owner: root
    group: root
    validate: 'visudo -cf %s'
